### PR TITLE
Initialize news page

### PR DESCRIPTION
**Pull request by anotherjoshsmith**
Probably put a little too much time into working on this... oops. I decided to add a "Featured Story" section to the `news.html` landing page to give it a little more substance. We can revert just to a page of links to full stories (basically dropping everything but the "Other News" section at the bottom) if we want. @pfaendtner let me know if you have a preference.

@jnnsmpth I decided to add your joining as the featured story for now, but you can change that if you'd like. Currently, it's just missing a one paragraph synopsis of your graduate research. Otherwise, just adding images (square if possible) and a brief description of each story you listed in #15 should be enough to get this merged for now.

### CODE REVIEW

**Comment by pfaendtner** [comment]
I like the featured story thing that sounds great!

**Comment by pfaendtner** [comment]
@anotherjoshsmith 1st time I've seen conflicts on a PR - I am going to click "resolve conflicts" and see what happens

**Comment by pfaendtner** [comment]
image

yeah I have no idea what this means 😢

**Comment by anotherjoshsmith** [comment]
omg... very silly conflict. I think the difference is just one extra space in the version on master.

@pfaendtner the code between `<<<<<<< intialize-news` and `>>>>>>>>> master` differs between the two branches. to resolve the merge conflict, you will need to choose the version of the code you want to be reflected in master after the merge. try clicking `Resolve conflicts` again and deleting lines 18 and 20-22. this will tell git that you prefer the version currently in `initialize-news`.

**Comment by anotherjoshsmith** [comment]
Should also explain the reason this causes a merge conflict...

The `initialize-news` branch is based off an old copy of the `master` branch. If, since the time of branching, all of the lines that have been changed in `initialize-news` had remained unchanged in `master`, we'd be able to go ahead and merge without any problems. However, sometime between the time that `initialize-news` was branched and now, I edited the conflicting line in another branch and the change was merged to `master`, so that this line doesn't look how `initialize-news` remembers.

**Pull request merged**
